###
POST localhost:8085/index
Content-Type: application/json

{
  "paths": ["/Users/victor/Downloads/temp/jinx"],
  "regEx" : "\\s+",
  "ignoredNames": [
    ".DS_Store"
  ]
}

###
POST localhost:8085/index
Content-Type: application/json

{
  "paths": ["/Users/victor/Downloads/temp/jinx/inner","/Users/victor/Downloads/temp/jinx/inner/bla.bla",
    "/Users/victor/Downloads/temp/jinx/runnerw.rc", "/Users/victor/Downloads/temp/jinx/abl.bla"]
}

###
POST localhost:8085/index
Content-Type: application/json

{
  "paths": ["/Users/victor/IdeaProjects/intellij-community"],
  "ignoredNames": [
    ".DS_Store"
  ]
}
###
POST localhost:8085/index
Content-Type: application/json

{
  "paths": ["/Users/victor/IdeaProjects/linux"],
  "ignoredNames": [
    ".DS_Store"
  ]
}


###
GET localhost:8085/index/dependency

###
GET localhost:8085/index/Hello
