### CREATE INDEX WITH CUSTOM REGEX
POST localhost:8085/index
Content-Type: application/json

{
  "paths": ["/Users/victor/Downloads/temp/jinx"],
  "regEx" : "\\s+",
  "ignoredNames": [
    ".DS_Store"
  ]
}

### CREATE INDEX WITH MULTIPLE PATHS
POST localhost:8085/index
Content-Type: application/json

{
  "paths": ["/Users/victor/Downloads/temp/jinx/inner","/Users/victor/Downloads/temp/jinx/inner/bla.bla",
    "/Users/victor/Downloads/temp/jinx/runnerw.rc", "/Users/victor/Downloads/temp/jinx/abl.bla"]
}


### DELETE INDEX
DELETE localhost:8085/index

### QUERY TOKEN FROM INDEX
GET localhost:8085/index/query/dependency
